// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ve9eJKZyDEX4lUycELicNTzsID7ARpk',
    appId: '1:229988350792:web:f450c25b611de00bc8117d',
    messagingSenderId: '229988350792',
    projectId: 'inclass-13-d8582',
    authDomain: 'inclass-13-d8582.firebaseapp.com',
    storageBucket: 'inclass-13-d8582.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGBykxFDW12CIkeKo6NFSChoyJgEl0J0',
    appId: '1:229988350792:android:6a2ae61411fbf395c8117d',
    messagingSenderId: '229988350792',
    projectId: 'inclass-13-d8582',
    storageBucket: 'inclass-13-d8582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0sZnynEdKYGoUr67aXFK6hS8U__wiWw',
    appId: '1:229988350792:ios:54714214da6cf1d8c8117d',
    messagingSenderId: '229988350792',
    projectId: 'inclass-13-d8582',
    storageBucket: 'inclass-13-d8582.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0sZnynEdKYGoUr67aXFK6hS8U__wiWw',
    appId: '1:229988350792:ios:54714214da6cf1d8c8117d',
    messagingSenderId: '229988350792',
    projectId: 'inclass-13-d8582',
    storageBucket: 'inclass-13-d8582.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ve9eJKZyDEX4lUycELicNTzsID7ARpk',
    appId: '1:229988350792:web:559e9e77ad70f457c8117d',
    messagingSenderId: '229988350792',
    projectId: 'inclass-13-d8582',
    authDomain: 'inclass-13-d8582.firebaseapp.com',
    storageBucket: 'inclass-13-d8582.firebasestorage.app',
  );
}
